### ISSUE TITLE
Create Probot app

### ISSUE THREAD

**Issue by gr2m** [squash-commit-app/squash-commit-app#1]
We could use https://github.com/probot/example-vercel as a starting point. In fact, I could have used it as template 🤷🏼 

I'm actually not 100% sure which permissions the app will need.

- The app will need to act on `pull_request.edited`
- In the event handler, we need to check if the pull request has a single commit. If it has 2 or more, we are done
- If it has a single commit, then create a new commit using. For that, we need to get the latest commit using `payload.pull_request.base.sha`, read the `data.commit.tree.sha` from the response, and then [create a new commit](https://docs.github.com/en/rest/reference/git#create-a-commit) setting `tree` to `data.commit.tree.sha` and `message` to an explanation of why this commit was created

**Comment by oscard0m** [comment]
Before moving forward with the creation of this app, a couple of points I'm don't have clear yet:
- Why creating a new Github App instead of opening a PR for the `Semantic Release` existing one?
- Why not doing a logic like:
	- `IF` It's a PR with one Commit
		- `IF` commit is NOT semantic compliant ->
			- `IF` title is NOT semantic compliant -> Do not allow to merge (with a check run maybe?)
			- `ELSE` use title
		- `ELSE` use commit #1
	- `ELSE` do nothing

**Comment by gr2m** [comment]
>     * Why creating a new Github App instead of opening a PR for the `Semantic Release` existing one?

The current Semantic Pull Request app is currently requesting the following permissions

<img width="440" alt="image" src="https://user-images.githubusercontent.com/39992/108927291-d8850b80-75f4-11eb-8d2a-5ab0270f33e9.png">

I'm pretty sure we will need the `contents:write` permission, we need to verify that. If it's true, we need a separate app because folks are not easily giving that permission to apps because it can be quite destructive when abused.

> Why not doing a logic like:

I think the app  would be useful outside the scope of semantic commits

**Comment by oscard0m** [comment]
> >     * Why creating a new Github App instead of opening a PR for the `Semantic Release` existing one?

> The current Semantic Pull Request app is currently requesting the following permissions

> <img width="440" alt="image" src="https://user-images.githubusercontent.com/39992/108927291-d8850b80-75f4-11eb-8d2a-5ab0270f33e9.png">

> I'm pretty sure we will need the `contents:write` permission, we need to verify that. If it's true, we need a separate app because folks are not easily giving that permission to apps because it can be quite destructive when abused.

Ah okay, I understand. You prefer a more explicit app which is clear why it's requesting write access. Sounds totally reasonable.

> > Why not doing a logic like:

> I think the app  would be useful outside the scope of semantic commits

Yep, definitely
