### ISSUE TITLE
App merged a Pull Request, something that should never happen

### ISSUE THREAD

**Issue by oscard0m** [squash-commit-app/squash-commit-app#16]
Squash Commit App should only add an extra commit to Pull Requests with one commit but it was found a pull request which was merged by the App:
https://github.com/octokit/request.js/pull/420

- [x] Suspended the App in `Octokit` GitHub organization until the issue is solved
- [x] Invalidated Private Keys associated to the app just in case this could be an attack
- [ ] To check Begin logs @gr2m 
- [x] To check octokit/request.js Webhook event logs @gr2m 
- [ ] Waiting answer to Github Community questions [[1]](https://github.community/t/is-it-possible-to-be-more-granular-when-giving-permissions-to-a-github-app/198457) [[2]](https://github.community/t/is-there-a-way-to-know-when-and-how-a-github-app-token-has-been-used/198472)

**Comment by oscard0m** [comment]
One cool action would be to be more granular on which permissions has squash-commit-app. Right now, when giving `read&write` access to [Contents](https://docs.github.com/en/rest/reference/permissions-required-for-github-apps#permission-on-contents) is opening the door to add commits to a branch (necessary) but also to merge pull requests (undesired). Do you know if this is possible @gr2m? (I already [posted the question in GitHub Community](https://github.community/t/is-it-possible-to-be-more-granular-when-giving-permissions-to-a-github-app/198457))

**Comment by oscard0m** [comment]
Reviewing Event details happened on the `squash-commit-app` I don't see any clue on who triggered that merge:

https://github.com/organizations/squash-commit-app/settings/apps/squash-commit-app/advanced -> and look for `2ab86410-0925-11ec-895e-e13d7a8e8253`

Maybe we could check https://github.com/octokit/request.js/settings/hooks but I guess we will find the same webhook probably.

Do we have any kind of logs in Begin?

---

Posted this question to GitHub Community in the meantime:
https://github.community/t/is-there-a-way-to-know-when-and-how-a-github-app-token-has-been-used/198472

**Comment by gr2m** [comment]
> One cool action would be to be more granular on which permissions has squash-commit-app

Unfortunately the granularity of permissions is a known problem. I don't think there is a better permission that we can use right now.

> https://github.com/octokit/request.js/settings/hooks

there are no manual webhooks setup

I also contacted support, they have tools like looking up requests authenticated by a certain actor I think, I hope they will be able to help us understand what's going on

**Comment by gr2m** [comment]
I got a response from GitHub Support

<img width="513" alt="image" src="https://user-images.githubusercontent.com/39992/133327765-d1ace202-ede0-4a0f-b0ff-8dfcba626d72.png">

good enough for me, I think we can close this issue now.

**Comment by oscard0m** [comment]
Nice! Mistery solved! I didn't know this `pull_request.indirect_merge` thing
