### ISSUE TITLE
Publish a semantic version of the app

### ISSUE THREAD

**Issue by gr2m** [squash-commit-app/squash-commit-app#7]
I'd like the app to only create an empty commit if the title is a semantic commit. That would also resolve the problem of #6 for me.

I would not introduce configuration to the app because it would slow it down significantly. I'd instead register a 2nd app that points to the same webhook handler, but in that handler select the right credentials based on the app ID in the webhook request payload

**Comment by gr2m** [comment]
Another thing we should consider: only react to when a pull request title was changed, do not on the initial creation of a pull request.

At least for me, the most common use case that I have a pull request with a single commit that was created automatically. I change the title after reviewing the changes to summarize what happened and then want to squash & commit. Between me changing the title and pressing the squash & commit button, I want the squash-commit-app to add the empty commit

**Comment by gr2m** [comment]
thinking more about it, I think we should make this ☝🏼  the default behavior of the app, what do you think @oscard0m?

**Comment by oscard0m** [comment]
> Another thing we should consider: only react to when a pull request title was changed, do not on the initial creation of a pull request.
> 
> At least for me, the most common use case that I have a pull request with a single commit that was created automatically. I change the title after reviewing the changes to summarize what happened and then want to squash & commit. Between me changing the title and pressing the squash & commit button, I want the squash-commit-app to add the empty commit

What about contributors with single commit PR's? DO they need to be aware of this (or the reviewers with edit rights to edit the title to trigger the bot?)

**Comment by oscard0m** [comment]
> thinking more about it, I think we should make this ☝🏼 the default behavior of the app, what do you think @oscard0m?

I have mixed feelings:
👍🏽  I like it would be triggered on demand (editing the title) so we could avoid the issues we are getting here:  
* https://github.com/squash-commit-app/squash-commit-app/issues/6
* https://github.com/squash-commit-app/squash-commit-app/issues/13
* https://github.com/squash-commit-app/squash-commit-app/issues/7

👎🏽  Contributors (or at least maintainers) need to be aware of this `edit-pr-title` so still, kind of semi-manual approach.

---

These are the steps I would follow:
1. Change the app to run only when PR title changes for the moment, so we remove friction and we make life easier for you and other users with the same use-case you have.
2. To create an issue to give support for automated (without editing the title) approach. Maybe with a `config.yml` file to override default behavior?

What do you think @gr2m

**Comment by gr2m** [comment]
I'd say we should give it a try and see if us or other users run into a problem with the app if it only acts on the edited event, but not the opened event.

Your suggestions sound good to me

**Comment by oscard0m** [comment]
> I'd say we should give it a try and see if us or other users run into a problem with the app if it only acts on the edited event, but not the opened event.
> 
> Your suggestions sound good to me

Hey @gr2m ! Did you have time to install the app on some or all Octokit repos? Did you have any issues?

**Comment by gr2m** [comment]
yes, I did, and it works great!

One thing that's a little annoying is that the extra commit triggers the CI again so when branch protection is enabled I have to wait for the CI to complete again (or to use the auto-merge feature). But there is nothing we can do about it, I still like it

**Comment by oscard0m** [comment]
> yes, I did, and it works great!
> 
> One thing that's a little annoying is that the extra commit triggers the CI again so when branch protection is enabled I have to wait for the CI to complete again (or to use the auto-merge feature). But there is nothing we can do about it, I still like it

I'm glad it works now 🥳 !

To not re-run CI seems a problem to the CI itself:
- CI check run execution times should be improved on those repos (if possible)
- To add some logic to workflows to not run when the commit is empty or if the `squash-commit-app` is the user doing the commit 
   - I can check the approach done internally here to get some ideas if you are interested into it? https://github.com/fkirc/skip-duplicate-actions

I can open a discussion in Octokit if you are interested @gr2m

**Comment by gr2m** [comment]
you could also add `[skip ci]` to the commit body to prevent most of the CI to re-run, but problem is that a pull request status is set by the commit statuses and checks set on its last commit, so the CI has to run, otherwise the pull request status will not turn green, because it's requiring some CI statuses to be set but it will never happen if the builds won't run
