### ISSUE TITLE
Move away from Vercel

### ISSUE THREAD

**Issue by gr2m** [squash-commit-app/squash-commit-app#8]
Turns out Vercel doesn't want to sponsor our little app, because it uses a serverless function. I'm not willing to pay $20/month for it just to stay at Vercel.

I'm open to suggestions. I really enjoyed Netlify lately, but I can also deploy it to @BeginCI, or something else? Cloudflare worker maybe? I'm open to suggestions

**Comment by ryanblock** [comment]
👋🏻 open to finding out!

**Comment by gr2m** [comment]
ha! Well that comment settles it, I'll move this to Begin :)

**Comment by gr2m** [comment]
@ryanblock is there a way I can configure the deployment branch? I'd like to deploy https://github.com/squash-commit-app/squash-commit-app/pull/10 while I'm working on it

**Comment by gr2m** [comment]
@ryanblock wait, ESM is not supported by begin/architect yet?

<img width="1211" alt="image" src="https://user-images.githubusercontent.com/39992/119584901-761be280-bd7e-11eb-86e4-6ff7ea3380f5.png">

**Comment by gr2m** [comment]
@ryanblock is it possible that my code in `src/http/post-api-github-webhooks/index.js` cannot access any code living above this folder?

<img width="1061" alt="image" src="https://user-images.githubusercontent.com/39992/119585423-87b1ba00-bd7f-11eb-9dff-b0b3669097c9.png">

**Comment by gr2m** [comment]
`squash-commit-app` is now running on Begin 🚀

**Comment by ryanblock** [comment]
Snap, that was fast! Sorry, just back from dinner. In order:
- ESM is not fully supported by Lambda yet, despite running a version of Node.js 14!
- As I'm guessing you've discovered (since you got it working!), once deployed Architect can't require modules outside of its own folder (since each folder represents a Lambda); to solve this we have the `src/shared` directory
Hope that helps, aim me at any stuff in your codebase you'd like a gander at, here to help!

**Comment by oscard0m** [comment]
> `squash-commit-app` is now running on Begin 🚀

Is there a chance to get access to this dashboard with the free plan (with limited privileges)? Or is an individual account? @gr2m 

> Turns out Vercel doesn't want to sponsor our little app, because it uses a serverless function. I'm not willing to pay $20/month for it just to stay at Vercel.

I assume you contacted them and they told you this. Should I contact them to update their terms here? https://vercel.com/support/articles/can-vercel-sponsor-my-open-source-project @gr2m 

> Snap, that was fast! Sorry, just back from dinner. In order:
> 
> * ESM is not fully supported by Lambda yet, despite running a version of Node.js 14!
> * As I'm guessing you've discovered (since you got it working!), once deployed Architect can't require modules outside of its own folder (since each folder represents a Lambda); to solve this we have the `src/shared` directory
>   Hope that helps, aim me at any stuff in your codebase you'd like a gander at, here to help!

Thanks for all the support here @ryanblock ❤️ 

In a quick search I did not find when AWS Lambda plans to support it: https://github.com/aws/aws-cdk/issues/13274 😢

**Comment by oscard0m** [comment]
> Turns out Vercel doesn't want to sponsor our little app, because it uses a serverless function. I'm not willing to pay $20/month for it just to stay at Vercel.

I assume you contacted them and they told you this. Should I contact them to update their terms here? https://vercel.com/support/articles/can-vercel-sponsor-my-open-source-project

**Comment by oscard0m** [comment]
> Snap, that was fast! Sorry, just back from dinner. In order:
> 
> * ESM is not fully supported by Lambda yet, despite running a version of Node.js 14!
> * As I'm guessing you've discovered (since you got it working!), once deployed Architect can't require modules outside of its own folder (since each folder represents a Lambda); to solve this we have the `src/shared` directory
>   Hope that helps, aim me at any stuff in your codebase you'd like a gander at, here to help!

Thanks for all the support here @ryanblock ❤️

**Comment by gr2m** [comment]
> I assume you contacted them and they told you this. Should I contact them to update their terms here? https://vercel.com/support/articles/can-vercel-sponsor-my-open-source-project @gr2m

Yes I did. I guess it is already included in this point:

> The project should be static rather than server-rendered.
